### ISSUE TITLE
[Question] Error during the maven install cannot find symbol "AppApplicationImpl"

### ISSUE THREAD

**Issue by p4535992** [NaluKit/nalu-examples#19]
Hi sorry again to bother, I have  integrated my libraries in your project (to check some library collision) and I get the following error:

```
[ERROR] [1;31mD:\ws-6.1\7.4\gwt-example-multimodule\nalu-simple-app-example-client\src\main\java\com\github\nalukit\nalu\simple\app\client\App.java:[44,37] error: cannot find symbol[m
[ERROR] [1;31m  symbol:   class AppApplicationImpl[m
[ERROR] [1;31m  location: class App
```
On this line: https://github.com/NaluKit/nalu-examples/blob/e09269dd25f5cd1e888f89c5de2277239bb93131/nalu-simple-app-example/nalu-simple-app-example-client/src/main/java/com/github/nalukit/nalu/simple/app/client/App.java#L44

Could the error be because I am using gwt version 2.9.0 instead of the version 2.10.0 ?

To make my use case as clear as possible I'll put the project that triggers the error here: https://github.com/p4535992/gwt-example-multimodule

Ty for your time

**Comment by FrankHossfeld** [comment]
The ** AppApplicationImpl** will be created by thew Nalu processor. So, yopu need to run **mvn clean compile* first.

> Could the error be because I am using gwt version 2.9.0 instead of the version 2.10.0 ?
That should not be a problem, but Nalu is tested against the latest GWT version and with next version requires Java 11.

**Comment by p4535992** [comment]
Ok for some reason the error was caused from the:
```
    <dependency>
      <groupId>org.fusesource.restygwt</groupId>
      <artifactId>restygwt</artifactId>
    </dependency>
```

ty again.

**Comment by p4535992** [comment]
A old one with GWT 2.8.2 and GXT 4.0.2, and a bunch of old code.

Keeping in mind that I just started three days ago to study gwt, your example was a great help for me to understand how to use the new gwt plugin with the new mechanism of multiple modules. 
And discovering Nalu wasn't a bad thing either, (maybe in the future  if i start a new project with gwt I will elaborate on this), but for now I just need to bring a very old project back to life.

Now I was able to compile successfully, but debugging still seems not to work, but probably due to my mistake.

Thanks again for this great example of GWT + Spring Boot

**Comment by FrankHossfeld** [comment]
Debugging should not be so hard. You need to start den codeserver first (and wait until you see the url in the output) and then start Spring Boot.

**Comment by p4535992** [comment]
@FrankHossfeld sorry to bother again... i must be very stupid .... how can i activate the debug on the client gwt side ?
I read the documentation and it should be fine add :
`
<arg>-agentlib:jdwp=transport=dt_socket,address=localhost:8000,server=y,suspend=y</arg>
`
 at this line  https://github.com/NaluKit/nalu-examples/blob/e09269dd25f5cd1e888f89c5de2277239bb93131/nalu-simple-app-example/nalu-simple-app-example-client/pom.xml#L105, but still is not seem to enable the debug on the client compiler.
 
 Did i miss something ? like some additional module on the xxx.gwt.xml ?

**Comment by FrankHossfeld** [comment]
np ...

run: **mvn gwt:codeserver -pl *-client -am (Windows: mvn gwt:devmode -pl *-client -am)** in one terminal window.

wait until you see the code server url inside the terminal. Something like that:

**[INFO] The code server is ready at http://127.0.0.1:9876/**

then run in another terminal window: **mvn spring-boot:run -P env-dev**

once the server is up, enter **http://localhost:8080/index.html** in the browser.

To debug, open the dev tools of you browser (use Chrome, Opera or FireFox), switch to sources, slect the Java Class you want to debug by **cmd+P** and enter classname. Then set a breakpoint

That's all.
